"""biotech_review_agent.py — Local literature review for biotech/clinical research.
Ingests PDF abstracts or .txt summaries, extracts fields, builds LOCAL_PAPERS.md,
cross-refs BRAIN.md/DECISIONS.md, runs gap analysis every 5 papers.
All processing local. Never sends patient/trial data anywhere.
"""
from __future__ import annotations
import re
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).parent
WIKI_DIR = BASE_DIR / "wiki"
PAPERS_DIR = WIKI_DIR / "papers"
LOCAL_PAPERS_PATH = WIKI_DIR / "LOCAL_PAPERS.md"
REVIEW_SUMMARY_PATH = BASE_DIR / "REVIEW_SUMMARY.md"
BRAIN_PATH = BASE_DIR / "BRAIN.md"
DECISIONS_PATH = BASE_DIR / "DECISIONS.md"

_papers_since_gap = 0
_GAP_EVERY = 5

def _now(): return datetime.now().strftime("%Y-%m-%d %H:%M")
def _today(): return datetime.now().strftime("%Y-%m-%d")
def _read(p): return p.read_text(encoding="utf-8") if p.exists() else ""
def _write(p, t): p.write_text(t, encoding="utf-8")
def _append(p, t):
    with open(p, "a", encoding="utf-8") as f: f.write(t)
def _slug(t): return re.sub(r"[^a-z0-9]+", "-", t.lower()).strip("-")[:60]

# ── Paper extraction ─────────────────────────────────────────────────

def extract_fields(text: str, filename: str = "") -> dict:
    """Extract title, authors, findings, methodology, limitations from text."""
    lines = [ln.strip() for ln in text.strip().splitlines() if ln.strip()]
    if not lines:
        return {"title": filename, "authors": "", "findings": "", "methodology": "", "limitations": ""}
    return {
        "title": _extract_field(lines, text, ["title:", "Title:"], lines[0][:120]),
        "authors": _extract_field(lines, text, ["Authors:", "Author:", "By:"], ""),
        "findings": _extract_section(text, ["finding", "result", "conclusion", "key finding", "outcome"]),
        "methodology": _extract_section(text, ["method", "design", "approach", "procedure", "protocol"]),
        "limitations": _extract_section(text, ["limitation", "weakness", "caveat", "constraint"]),
    }

def _extract_field(lines, text, markers, fallback=""):
    for marker in markers:
        for line in lines:
            if line.lower().startswith(marker.lower()):
                val = line[len(marker):].strip().lstrip(":").strip()
                if val: return val
    return fallback

def _extract_section(text, keywords):
    low = text.lower()
    for kw in keywords:
        for pat in [rf"(?:^|\n)\s*(?:#+\s*)?{kw}s?\s*[:：]\s*(.+?)(?=\n\s*(?:#+|[A-Z][a-z]+:)|\Z)",
                    rf"(?:^|\n)\s*(?:#+\s*)?{kw}s?\s*\n(.+?)(?=\n\s*(?:#+|[A-Z][a-z]+:)|\Z)"]:
            m = re.search(pat, low, re.DOTALL | re.IGNORECASE)
            if m:
                raw = text[m.start(1):m.end(1)].strip()
                return raw[:500] if raw else ""
    return ""

# ── Paper index ──────────────────────────────────────────────────────

def _add_to_index(fields: dict, source_file: str):
    PAPERS_DIR.mkdir(parents=True, exist_ok=True)
    if not LOCAL_PAPERS_PATH.exists():
        _write(LOCAL_PAPERS_PATH, f"# Local Papers Index\n\n_Auto-generated by biotech_review_agent. Updated: {_today()}_\n\n")
    entry = (f"---\n\n### {fields['title']}\n"
             f"- **Source:** {source_file}\n- **Authors:** {fields['authors'] or 'Not specified'}\n"
             f"- **Findings:** {fields['findings'][:200] or 'See full text'}\n"
             f"- **Method:** {fields['methodology'][:150] or 'Not specified'}\n"
             f"- **Limitations:** {fields['limitations'][:150] or 'Not stated'}\n"
             f"- **Indexed:** {_today()}\n")
    _append(LOCAL_PAPERS_PATH, entry + "\n")
    slug = _slug(fields["title"]) or _slug(source_file)
    _write(PAPERS_DIR / f"{slug}.md",
           f"---\ntitle: {fields['title']}\ntype: paper\nauthors: {fields['authors']}\nindexed: {_today()}\n---\n\n"
           f"## Key Findings\n{fields['findings'] or 'Not extracted.'}\n\n"
           f"## Methodology\n{fields['methodology'] or 'Not extracted.'}\n\n"
           f"## Limitations\n{fields['limitations'] or 'Not stated.'}\n")

# ── Cross-reference with memory ──────────────────────────────────────

def cross_reference(fields: dict) -> list[str]:
    """Check BRAIN.md and DECISIONS.md for related context."""
    flags, brain, decisions = [], _read(BRAIN_PATH).lower(), _read(DECISIONS_PATH).lower()
    combined = fields["title"].lower() + " " + fields["findings"].lower()
    for term in _extract_key_terms(combined):
        if term in brain: flags.append(f"BRAIN.md mentions '{term}' — check for alignment")
        if term in decisions: flags.append(f"DECISIONS.md has prior entry about '{term}' — verify consistency")
    return flags

def _extract_key_terms(text: str) -> list[str]:
    compounds = re.findall(r"\b\w*(?:tide|mab|nib|pril|statin|zole|pine|ine|ase)\b", text, re.IGNORECASE)
    diseases = re.findall(r"\b(?:diabetes|obesity|cancer|alzheimer|parkinson|hiv|copd|hypertension|"
        r"cardiovascular|hepatitis|fibrosis|inflammation|metabolic|autoimmune|neurodegeneration)\b", text, re.IGNORECASE)
    methods = re.findall(r"\b(?:rct|randomized|placebo|double.blind|meta.analysis|cohort|retrospective|"
        r"prospective|phase\s*[i-v]+|in\s*vitro|in\s*vivo|pcr|elisa|western\s*blot)\b", text, re.IGNORECASE)
    all_terms = set(t.lower().strip() for t in compounds + diseases + methods)
    return [t for t in all_terms if len(t) > 3]

# ── Gap analysis ─────────────────────────────────────────────────────

def run_gap_analysis() -> str:
    index = _read(LOCAL_PAPERS_PATH)
    if not index: return "No papers indexed yet."
    papers = index.split("---")
    paper_count = sum(1 for p in papers if "###" in p)
    all_findings, all_limitations, all_methods = [], [], set()
    for block in papers:
        f = re.search(r"\*\*Findings:\*\*\s*(.+?)$", block, re.MULTILINE)
        if f: all_findings.append(f.group(1).strip())
        l = re.search(r"\*\*Limitations:\*\*\s*(.+?)$", block, re.MULTILINE)
        if l and "not stated" not in l.group(1).lower(): all_limitations.append(l.group(1).strip())
        m = re.search(r"\*\*Method:\*\*\s*(.+?)$", block, re.MULTILINE)
        if m: all_methods.add(m.group(1).strip()[:60])

    gaps = [f"## Gap Analysis — {_today()}\n", f"**Papers reviewed:** {paper_count}\n",
            f"**Methods represented:** {', '.join(all_methods) or 'None extracted'}\n"]
    if all_limitations:
        gaps.append(f"\n### Recurring Limitations")
        gaps.extend(f"- {lim}" for lim in all_limitations[:5])
    gaps.append(f"\n### Questions This Literature Has Not Answered")
    if paper_count < 3:
        gaps.append("- Insufficient papers for meaningful gap identification")
    else:
        checks = [("long|duration", all_limitations, "Long-term outcomes beyond study duration"),
                   ("diverse|population", all_limitations, "Generalizability across diverse populations"),
                   ("mechanism", all_findings, "Underlying mechanism of action not fully explored"),
                   ("cost|economic", all_findings, "Cost-effectiveness and health economics data"),
                   ("head|versus|compar", all_findings, "Head-to-head comparison studies between agents")]
        for pat, src, msg in checks:
            if not any(re.search(pat, s, re.IGNORECASE) for s in src): gaps.append(f"- {msg}")
    return "\n".join(gaps)

# ── Review summary builder ───────────────────────────────────────────

def build_review_summary() -> str:
    index = _read(LOCAL_PAPERS_PATH)
    if not index: return "No papers to summarize."
    parts = [f"# Literature Review Summary\n", f"_Generated: {_now()} by OpenClay biotech_review_agent_\n",
             f"_All processing performed locally. No data sent externally._\n",
             f"\n## Papers Reviewed\n", index, f"\n{run_gap_analysis()}\n", f"\n## Cross-References\n"]
    xrefs, decisions = _read(BRAIN_PATH), _read(DECISIONS_PATH)
    if "compound" in xrefs.lower() or "drug" in xrefs.lower():
        parts.append("- BRAIN.md contains prior compound/drug context\n")
    if decisions and "###" in decisions:
        parts.append(f"- DECISIONS.md has {decisions.count('###')} prior entries that may relate to this review\n")
    parts.append(f"\n## Suggested Next Steps\n")
    try:
        from predict_engine import predict
        for s in predict("biotech literature review paper"): parts.append(f"- {s}")
    except Exception:
        parts.extend(["- Write hypothesis based on gap analysis", "- Update protocol with new findings",
                       "- Search for contradicting studies"])
    summary = "\n".join(parts)
    _write(REVIEW_SUMMARY_PATH, summary + "\n")
    return summary

# ── Main ingest pipeline ─────────────────────────────────────────────

def ingest_folder(folder: str | Path) -> dict:
    global _papers_since_gap
    folder = Path(folder)
    if not folder.exists(): return {"ingested": 0, "flags": [], "gap_analysis": "", "summary_path": ""}
    files = sorted(list(folder.glob("*.txt")) + list(folder.glob("*.pdf")))
    all_flags, ingested, gap_text = [], 0, ""
    for f in files:
        try: text = f.read_text(encoding="utf-8", errors="ignore")
        except Exception: continue
        if not text.strip(): continue
        fields = extract_fields(text, f.name)
        _add_to_index(fields, f.name)
        all_flags.extend(cross_reference(fields))
        ingested += 1; _papers_since_gap += 1
        if _papers_since_gap >= _GAP_EVERY: gap_text = run_gap_analysis(); _papers_since_gap = 0
    build_review_summary()
    return {"ingested": ingested, "flags": all_flags, "gap_analysis": gap_text, "summary_path": str(REVIEW_SUMMARY_PATH)}

def get_suggestions() -> list[str]:
    return ["Write a hypothesis based on the gap analysis",
            "Update protocol document with new findings",
            "Search for studies that contradict current conclusions"]

# ── Self test ────────────────────────────────────────────────────────

def self_test() -> bool:
    import tempfile, shutil
    tmp = Path(tempfile.mkdtemp())
    try:
        sample = tmp / "sample_abstract.txt"
        sample.write_text(
            "Title: Effects of Semaglutide on Body Weight in Obesity\n"
            "Authors: Jensen AB, Knop FK, Lundgren JR\n"
            "Methods: Randomized, double-blind, placebo-controlled trial. N=1961 adults with BMI>=30.\n"
            "Results: Semaglutide 2.4mg weekly resulted in 14.9% mean body weight reduction vs 2.4% with placebo.\n"
            "Limitations: Short follow-up period. Predominantly white cohort.\n", encoding="utf-8")
        fields = extract_fields(sample.read_text(), "sample_abstract.txt")
        assert "Semaglutide" in fields["title"], f"title: {fields['title']}"
        assert fields["authors"], "authors empty"
        assert isinstance(cross_reference(fields), list)
        terms = _extract_key_terms("semaglutide diabetes obesity rct")
        assert any("semaglutide" in t for t in terms) and any("diabetes" in t for t in terms)
        assert isinstance(run_gap_analysis(), str)
        assert len(get_suggestions()) == 3
        if LOCAL_PAPERS_PATH.exists():
            idx = _read(LOCAL_PAPERS_PATH)
            if "sample_abstract" in idx:
                parts = idx.split("---")
                _write(LOCAL_PAPERS_PATH, "---".join(p for p in parts if "sample_abstract" not in p) or "")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    return True

if __name__ == "__main__":
    print("self_test:", self_test())
