"""biotech_review_agent.py — Local literature review for biotech/clinical research.

Ingests folders of PDF abstracts or .txt paper summaries, extracts structured
fields (title, authors, findings, methodology, limitations), builds a
LOCAL_PAPERS.md index in the wiki, cross-references BRAIN.md and DECISIONS.md
for contradictions/confirmations, runs gap analysis every 5 papers, and
outputs REVIEW_SUMMARY.md ready for grant applications or protocol documents.

All processing is local. No API calls for the papers themselves.
Never sends patient data or trial data anywhere.
"""
from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).parent
WIKI_DIR = BASE_DIR / "wiki"
PAPERS_DIR = WIKI_DIR / "papers"
LOCAL_PAPERS_PATH = WIKI_DIR / "LOCAL_PAPERS.md"
REVIEW_SUMMARY_PATH = BASE_DIR / "REVIEW_SUMMARY.md"
BRAIN_PATH = BASE_DIR / "BRAIN.md"
DECISIONS_PATH = BASE_DIR / "DECISIONS.md"

_papers_since_gap = 0
_GAP_EVERY = 5


def _now(): return datetime.now().strftime("%Y-%m-%d %H:%M")
def _today(): return datetime.now().strftime("%Y-%m-%d")
def _read(p): return p.read_text(encoding="utf-8") if p.exists() else ""
def _write(p, t): p.write_text(t, encoding="utf-8")
def _append(p, t):
    with open(p, "a", encoding="utf-8") as f:
        f.write(t)
def _slug(t): return re.sub(r"[^a-z0-9]+", "-", t.lower()).strip("-")[:60]


# ── Paper extraction ─────────────────────────────────────────────────

def extract_fields(text: str, filename: str = "") -> dict:
    """Extract structured fields from a paper abstract or summary.

    Returns dict with: title, authors, findings, methodology, limitations.
    All extraction is local — regex + heuristic, no API calls.
    """
    lines = [ln.strip() for ln in text.strip().splitlines() if ln.strip()]
    if not lines:
        return {"title": filename, "authors": "", "findings": "",
                "methodology": "", "limitations": ""}

    title = _extract_field(lines, text, ["title:", "Title:"],
                           fallback=lines[0][:120])
    authors = _extract_field(lines, text, ["Authors:", "Author:", "By:"],
                             fallback="")
    findings = _extract_section(text, ["finding", "result", "conclusion",
                                       "key finding", "outcome"])
    methodology = _extract_section(text, ["method", "design", "approach",
                                          "procedure", "protocol"])
    limitations = _extract_section(text, ["limitation", "weakness",
                                          "caveat", "constraint"])
    return {
        "title": title, "authors": authors, "findings": findings,
        "methodology": methodology, "limitations": limitations,
    }


def _extract_field(lines, text, markers, fallback=""):
    """Find a labeled field like 'Title: ...' in the text."""
    for marker in markers:
        for line in lines:
            if line.lower().startswith(marker.lower()):
                val = line[len(marker):].strip().lstrip(":").strip()
                if val:
                    return val
    return fallback


def _extract_section(text, keywords):
    """Extract a section that follows a keyword header."""
    low = text.lower()
    for kw in keywords:
        # Try "Keyword:" or "## Keyword" patterns
        for pat in [rf"(?:^|\n)\s*(?:#+\s*)?{kw}s?\s*[:：]\s*(.+?)(?=\n\s*(?:#+|[A-Z][a-z]+:)|\Z)",
                    rf"(?:^|\n)\s*(?:#+\s*)?{kw}s?\s*\n(.+?)(?=\n\s*(?:#+|[A-Z][a-z]+:)|\Z)"]:
            m = re.search(pat, low, re.DOTALL | re.IGNORECASE)
            if m:
                raw = text[m.start(1):m.end(1)].strip()
                return raw[:500] if raw else ""
    return ""


# ── Paper index ──────────────────────────────────────────────────────

def _add_to_index(fields: dict, source_file: str):
    """Add one paper entry to LOCAL_PAPERS.md."""
    PAPERS_DIR.mkdir(parents=True, exist_ok=True)
    if not LOCAL_PAPERS_PATH.exists():
        _write(LOCAL_PAPERS_PATH, f"# Local Papers Index\n\n"
               f"_Auto-generated by biotech_review_agent. "
               f"Updated: {_today()}_\n\n")

    entry = (f"---\n\n### {fields['title']}\n"
             f"- **Source:** {source_file}\n"
             f"- **Authors:** {fields['authors'] or 'Not specified'}\n"
             f"- **Findings:** {fields['findings'][:200] or 'See full text'}\n"
             f"- **Method:** {fields['methodology'][:150] or 'Not specified'}\n"
             f"- **Limitations:** {fields['limitations'][:150] or 'Not stated'}\n"
             f"- **Indexed:** {_today()}\n")
    _append(LOCAL_PAPERS_PATH, entry + "\n")

    # Save individual paper page in wiki/papers/
    slug = _slug(fields["title"]) or _slug(source_file)
    paper_path = PAPERS_DIR / f"{slug}.md"
    page = (f"---\ntitle: {fields['title']}\ntype: paper\n"
            f"authors: {fields['authors']}\nindexed: {_today()}\n---\n\n"
            f"## Key Findings\n{fields['findings'] or 'Not extracted.'}\n\n"
            f"## Methodology\n{fields['methodology'] or 'Not extracted.'}\n\n"
            f"## Limitations\n{fields['limitations'] or 'Not stated.'}\n")
    _write(paper_path, page)


# ── Cross-reference with memory ──────────────────────────────────────

def cross_reference(fields: dict) -> list[str]:
    """Check BRAIN.md and DECISIONS.md for related past context.

    Returns list of flags: contradictions, confirmations, or related notes.
    """
    flags = []
    brain = _read(BRAIN_PATH).lower()
    decisions = _read(DECISIONS_PATH).lower()
    combined = fields["title"].lower() + " " + fields["findings"].lower()

    # Extract key terms (compounds, diseases, methods)
    terms = _extract_key_terms(combined)

    for term in terms:
        if term in brain:
            flags.append(f"BRAIN.md mentions '{term}' — check for alignment")
        if term in decisions:
            # Check if the decision outcome contradicts the finding
            flags.append(f"DECISIONS.md has prior entry about '{term}' — "
                         f"verify consistency")
    return flags


def _extract_key_terms(text: str) -> list[str]:
    """Pull likely biotech terms from text (compounds, diseases, methods)."""
    # Common biotech compound/drug suffixes
    compounds = re.findall(
        r"\b\w*(?:tide|mab|nib|pril|statin|zole|pine|ine|ase)\b",
        text, re.IGNORECASE
    )
    # Disease/condition terms (3+ chars, capitalized in original or known)
    diseases = re.findall(
        r"\b(?:diabetes|obesity|cancer|alzheimer|parkinson|hiv|copd|"
        r"hypertension|cardiovascular|hepatitis|fibrosis|inflammation|"
        r"metabolic|autoimmune|neurodegeneration)\b",
        text, re.IGNORECASE
    )
    # Method terms
    methods = re.findall(
        r"\b(?:rct|randomized|placebo|double.blind|meta.analysis|"
        r"cohort|retrospective|prospective|phase\s*[i-v]+|"
        r"in\s*vitro|in\s*vivo|pcr|elisa|western\s*blot)\b",
        text, re.IGNORECASE
    )
    all_terms = set(t.lower().strip() for t in compounds + diseases + methods)
    # Filter out very short or common words
    return [t for t in all_terms if len(t) > 3]


# ── Gap analysis ─────────────────────────────────────────────────────

def run_gap_analysis() -> str:
    """Analyze LOCAL_PAPERS.md for unanswered questions.

    Checks methodology coverage, limitation patterns, and missing areas.
    """
    index = _read(LOCAL_PAPERS_PATH)
    if not index:
        return "No papers indexed yet."

    papers = index.split("---")
    paper_count = sum(1 for p in papers if "###" in p)
    # Collect all findings and limitations
    all_findings = []
    all_limitations = []
    all_methods = set()
    for block in papers:
        f_match = re.search(r"\*\*Findings:\*\*\s*(.+?)$", block, re.MULTILINE)
        if f_match:
            all_findings.append(f_match.group(1).strip())
        l_match = re.search(r"\*\*Limitations:\*\*\s*(.+?)$", block, re.MULTILINE)
        if l_match and "not stated" not in l_match.group(1).lower():
            all_limitations.append(l_match.group(1).strip())
        m_match = re.search(r"\*\*Method:\*\*\s*(.+?)$", block, re.MULTILINE)
        if m_match:
            all_methods.add(m_match.group(1).strip()[:60])

    gaps = [f"## Gap Analysis — {_today()}\n",
            f"**Papers reviewed:** {paper_count}\n",
            f"**Methods represented:** {', '.join(all_methods) or 'None extracted'}\n"]
    # Identify limitation clusters
    if all_limitations:
        gaps.append(f"\n### Recurring Limitations")
        for lim in all_limitations[:5]:
            gaps.append(f"- {lim}")
    # Identify what's missing
    gaps.append(f"\n### Questions This Literature Has Not Answered")
    if paper_count < 3:
        gaps.append("- Insufficient papers for meaningful gap identification")
    else:
        if not any("long" in l.lower() or "duration" in l.lower()
                    for l in all_limitations):
            gaps.append("- Long-term outcomes beyond study duration")
        if not any("diverse" in l.lower() or "population" in l.lower()
                    for l in all_limitations):
            gaps.append("- Generalizability across diverse populations")
        if not any("mechanism" in f.lower() for f in all_findings):
            gaps.append("- Underlying mechanism of action not fully explored")
        if not any("cost" in f.lower() or "economic" in f.lower()
                    for f in all_findings):
            gaps.append("- Cost-effectiveness and health economics data")
        if not any("head" in f.lower() or "versus" in f.lower()
                    or "compar" in f.lower() for f in all_findings):
            gaps.append("- Head-to-head comparison studies between agents")

    return "\n".join(gaps)


# ── Review summary builder ───────────────────────────────────────────

def build_review_summary() -> str:
    """Build REVIEW_SUMMARY.md from all indexed papers + gap analysis."""
    index = _read(LOCAL_PAPERS_PATH)
    if not index:
        return "No papers to summarize."

    parts = [
        f"# Literature Review Summary\n",
        f"_Generated: {_now()} by OpenClay biotech_review_agent_\n",
        f"_All processing performed locally. No data sent externally._\n",
        f"\n## Papers Reviewed\n",
        index,
        f"\n{run_gap_analysis()}\n",
        f"\n## Cross-References\n",
    ]
    # Add any cross-reference flags
    xrefs = _read(BRAIN_PATH)
    if "compound" in xrefs.lower() or "drug" in xrefs.lower():
        parts.append("- BRAIN.md contains prior compound/drug context\n")
    decisions = _read(DECISIONS_PATH)
    if decisions and "###" in decisions:
        parts.append(f"- DECISIONS.md has {decisions.count('###')} prior entries "
                     f"that may relate to this review\n")
    parts.append(f"\n## Suggested Next Steps\n")
    try:
        from predict_engine import predict
        for s in predict("biotech literature review paper"):
            parts.append(f"- {s}")
    except Exception:
        parts.append("- Write hypothesis based on gap analysis")
        parts.append("- Update protocol with new findings")
        parts.append("- Search for contradicting studies")

    summary = "\n".join(parts)
    _write(REVIEW_SUMMARY_PATH, summary + "\n")
    return summary


# ── Main ingest pipeline ─────────────────────────────────────────────

def ingest_folder(folder: str | Path) -> dict:
    """Ingest all .txt and .pdf abstracts from a folder.

    Returns: {ingested: int, flags: list, gap_analysis: str, summary_path: str}
    """
    global _papers_since_gap
    folder = Path(folder)
    if not folder.exists():
        return {"ingested": 0, "flags": [], "gap_analysis": "",
                "summary_path": ""}

    files = sorted(list(folder.glob("*.txt")) + list(folder.glob("*.pdf")))
    all_flags = []
    ingested = 0
    gap_text = ""

    for f in files:
        # Read text content (skip binary PDFs — only text-based)
        try:
            text = f.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if not text.strip():
            continue

        fields = extract_fields(text, f.name)
        _add_to_index(fields, f.name)
        flags = cross_reference(fields)
        all_flags.extend(flags)
        ingested += 1
        _papers_since_gap += 1

        if _papers_since_gap >= _GAP_EVERY:
            gap_text = run_gap_analysis()
            _papers_since_gap = 0

    # Build final summary
    summary = build_review_summary()
    return {
        "ingested": ingested,
        "flags": all_flags,
        "gap_analysis": gap_text,
        "summary_path": str(REVIEW_SUMMARY_PATH),
    }


# ── Predict engine integration ───────────────────────────────────────

def get_suggestions() -> list[str]:
    """Post-ingest suggestions for predict_engine."""
    return [
        "Write a hypothesis based on the gap analysis",
        "Update protocol document with new findings",
        "Search for studies that contradict current conclusions",
    ]


# ── Self test ────────────────────────────────────────────────────────

def self_test() -> bool:
    """Verify biotech_review_agent extraction, indexing, and analysis."""
    import tempfile, shutil

    # Create temp folder with a sample abstract
    tmp = Path(tempfile.mkdtemp())
    try:
        sample = tmp / "sample_abstract.txt"
        sample.write_text(
            "Title: Effects of Semaglutide on Body Weight in Obesity\n"
            "Authors: Jensen AB, Knop FK, Lundgren JR\n"
            "Methods: Randomized, double-blind, placebo-controlled trial. "
            "N=1961 adults with BMI>=30. 68-week treatment period.\n"
            "Results: Semaglutide 2.4mg weekly resulted in 14.9% mean body "
            "weight reduction vs 2.4% with placebo (p<0.001).\n"
            "Limitations: Short follow-up period. Predominantly white cohort. "
            "Gastrointestinal side effects not fully characterized.\n",
            encoding="utf-8",
        )

        # Extraction
        text = sample.read_text()
        fields = extract_fields(text, "sample_abstract.txt")
        assert "Semaglutide" in fields["title"], f"title: {fields['title']}"
        assert fields["authors"], "authors empty"
        assert "14.9%" in fields["findings"] or "weight" in fields["findings"].lower(), \
            f"findings: {fields['findings']}"

        # Cross-reference (should work even with empty BRAIN/DECISIONS)
        flags = cross_reference(fields)
        assert isinstance(flags, list), "flags must be list"

        # Key term extraction
        terms = _extract_key_terms("semaglutide diabetes obesity rct")
        assert any("semaglutide" in t for t in terms), f"terms: {terms}"
        assert any("diabetes" in t for t in terms), f"terms: {terms}"

        # Gap analysis
        gap = run_gap_analysis()
        assert isinstance(gap, str), "gap must be string"

        # Suggestions
        sug = get_suggestions()
        assert len(sug) == 3, "expected 3 suggestions"

        # Clean up test artifacts from LOCAL_PAPERS.md
        if LOCAL_PAPERS_PATH.exists():
            idx = _read(LOCAL_PAPERS_PATH)
            if "sample_abstract" in idx:
                # Remove the test entry
                parts = idx.split("---")
                cleaned = "---".join(
                    p for p in parts if "sample_abstract" not in p
                )
                _write(LOCAL_PAPERS_PATH, cleaned if cleaned.strip() else "")

    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    return True
